"""Render unmodified Isaac Lab triangle meshes using MuJoCo's offscreen renderer."""
import json
import sys
from pathlib import Path
import xml.etree.ElementTree as ET
import mujoco
import numpy as np
from PIL import Image

folder = Path(sys.argv[1])
out = folder / "mesh_renders"
out.mkdir(exist_ok=True)
manifest = json.loads((folder / "mesh_manifest.json").read_text(encoding="utf-8"))
manifest["renderer"] = "MuJoCo offscreen rendering of original Isaac Lab triangle meshes"
manifest["note"] = "Geometry is generated by current Isaac Lab functions; only render engine and display colors differ."
for item in manifest["terrains"]:
    stem = item["image"].replace(".png", "")
    root = ET.Element("mujoco")
    ET.SubElement(root, "compiler", angle="degree")
    visual = ET.SubElement(root, "visual")
    ET.SubElement(visual, "global", offwidth="800", offheight="700")
    ET.SubElement(visual, "headlight", ambient=".35 .35 .35", diffuse=".7 .7 .7", specular=".1 .1 .1")
    ET.SubElement(visual, "rgba", haze=".93 .95 .97 1")
    assets = ET.SubElement(root, "asset")
    ET.SubElement(assets, "texture", name="sky", type="skybox", builtin="gradient", rgb1=".91 .94 .97", rgb2=".97 .98 .99", width="512", height="512")
    ET.SubElement(assets, "mesh", name="terrain", file=(folder / f"{stem}.obj").as_posix(), inertia="shell")
    world = ET.SubElement(root, "worldbody")
    ET.SubElement(world, "light", pos="-3 -4 12", dir=".2 .2 -1", directional="true", diffuse=".7 .7 .7")
    color = ".38 .58 .66 1" if item["preset"] == "rough" else ".67 .49 .28 1"
    ET.SubElement(world, "geom", type="mesh", mesh="terrain", rgba=color, contype="0", conaffinity="0")
    model = mujoco.MjModel.from_xml_string(ET.tostring(root, encoding="unicode"))
    data = mujoco.MjData(model)
    mujoco.mj_forward(model, data)
    camera = mujoco.MjvCamera()
    camera.type = mujoco.mjtCamera.mjCAMERA_FREE
    camera.lookat[:] = [0, 0, item["bounds"][1][2] - .1]
    camera.azimuth = 125
    camera.elevation = -52
    camera.distance = 16
    with mujoco.Renderer(model, height=700, width=800) as renderer:
        renderer.update_scene(data, camera)
        Image.fromarray(renderer.render()).save(out / item["image"])
        if item["name"] in ("star", "gap", "stepping_stones"):
            camera.azimuth = 90
            camera.elevation = -89.9
            camera.distance = 12
            renderer.update_scene(data, camera)
            Image.fromarray(renderer.render()).save(out / f"{stem}__top.png")
    print(f"RENDERED {stem}", flush=True)
(out / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
print("MESH_RENDERS_COMPLETE", flush=True)
