"""Checks against real commands, articulation writes and reset lifecycle."""
import copy
import torch
from isal2.tasks.common.reference.commands import push_base_horizontal


def check_reference(env):
    raw = env.unwrapped
    t, command = raw.scene.terrain, raw.command_generator
    ids = torch.tensor([0],device=env.device)
    state = raw.reference_state_dict()
    assert raw.cfg.noise.add_noise and raw.cfg.noise.noise_scales.height_scan == 0
    assert raw.cfg.scene.height_scanner.drift_range == (0.,0.)
    assert command.cfg.resampling_time_range == (10.,10.)
    assert command.cfg.rel_standing_envs == 0 and command.cfg.rel_heading_envs == 1
    assert command.cfg.ranges.lin_vel_x == (0.,1.5)
    # All commands are generated by the same standard term used by rewards/obs.
    all_ids = torch.arange(env.num_envs,device=env.device)
    for _ in range(20):
        command.reset(all_ids)
        command._update_command()
        assert ((command.command[:,0]>=0)&(command.command[:,0]<=1.5)).all()
        assert (command.command[:,1]==0).all() and (command.command[:,2].abs()<=1).all()
        assert not command.is_standing_env.any()
        if raw.cfg.reference.stage == 2:
            assert not command.heading_target.any()
    previous = command.command[:,:2].clone()
    command.compute(9.99)
    assert torch.equal(command.command[:,:2],previous)
    command.compute(.02)
    assert not torch.equal(command.command[:,:2],previous)
    assert torch.allclose(command.time_left,torch.full_like(command.time_left,10.))
    from isaaclab.utils.math import wrap_to_pi
    expected_yaw = (.5*wrap_to_pi(command.heading_target-raw.robot.data.heading_w)).clamp(-1,1)
    assert torch.allclose(command.command[:,2],expected_yaw)
    env.reset()
    expected_yaw = (.5*wrap_to_pi(command.heading_target-raw.robot.data.heading_w)).clamp(-1,1)
    assert torch.allclose(command.command[:,2],expected_yaw), 'First reset observation contains an unresolved yaw command'
    assert torch.equal(t.terrain_levels,state['levels'])
    assert torch.equal(t.terrain_types,state['columns'])
    raw._reset_idx(ids)
    assert torch.equal(t.terrain_levels,state['levels'])
    # Exercise actual curriculum with a known root displacement and current command.
    pose = raw.robot.data.root_state_w[ids,:7].clone()
    pose[:,:3] = raw.scene.env_origins[ids]
    pose[:,0] += 4.01
    raw.robot.write_root_pose_to_sim(pose,ids)
    t.terrain_levels[0] = 3
    raw._automatic_reset = True
    raw._update_curriculum(ids)
    assert t.terrain_levels[0] == 4
    assert torch.equal(t.terrain_levels[1:],state['levels'][1:])
    assert torch.equal(t.terrain_types,state['columns'])
    raw._automatic_reset = False
    raw.load_reference_state_dict(state)
    env.reset()
    if raw.cfg.reference.stage == 2:
        before = raw.robot.data.root_vel_w.clone()
        push_base_horizontal(raw,ids)
        after = raw.robot.data.root_vel_w.clone()
        assert (after[ids,:2]-before[ids,:2]).abs().max() <= .10001
        assert torch.equal(after[ids,2:],before[ids,2:])
        assert torch.equal(after[1:],before[1:])
        env.reset()
    raw.episode_length_buf[0] = raw.max_episode_length-1
    _,_,done,extras = env.step(torch.zeros(env.num_envs,env.num_actions,device=env.device))
    assert done[0] and extras['time_outs'][0]
    assert not raw.reset_terminated[0]
    assert 'terminal_observation' in extras
    # Failure takes priority over timeout for bootstrap and termination reward.
    from isal2.tasks.common.base.mdp.rewards import is_terminated
    raw.reset_terminated[0] = True
    raw.reset_time_outs[0] = True
    assert is_terminated(raw)[0]
    env.reset()
    raw.load_reference_state_dict(state)
    env.reset()
    return dict(distance_curriculum=True, fixed_columns=True, manual_and_partial_reset=True,
        timeout_bootstrap=True, clean_scan=True, commands=True,
        additive_push=raw.cfg.reference.stage==2)


def check_config_regression(cfg):
    # Deliberately import archived configs only in this regression test.
    from isal2.deprecated_tasks.endpoint_course.ame_stage1.env_cfg import RPOAMEStage1EnvCfg
    from isal2.deprecated_tasks.endpoint_course.ame_stage2.env_cfg import RPOAMEStage2EnvCfg
    old = (RPOAMEStage1EnvCfg if cfg.reference.stage == 1 else RPOAMEStage2EnvCfg)()
    old.configure(num_envs=cfg.scene_context.num_envs)
    for name in ('robot','noise','normalization'):
        assert getattr(cfg,name).to_dict() == getattr(old,name).to_dict(),name
    for name,value in cfg.reward.to_dict().items():
        expected = copy.deepcopy(old.reward.to_dict()[name])
        actual = copy.deepcopy(value)
        if name == 'termination_penalty':
            expected.pop('func'); actual.pop('func')
        assert actual == expected,name
    for name,value in cfg.events.to_dict().items():
        if name in ('reset_base','push_robot'):
            continue
        assert value == old.events.to_dict()[name],name
    assert cfg.scene.robot.to_dict() == old.scene.robot.to_dict()
    return True
